services:
  app:
    container_name: app_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    environment:
      APP_URL: https://www.juzwystawiam.pl
      ASSET_URL: https://www.juzwystawiam.pl
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: db_prod
      DB_USERNAME: db_prod_user
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ENV: production
      APP_DEBUG: false
      VITE_APP_NAME: JuzWystawiam
      APP_NAME: JuzWystawiam
      MAIL_FROM_ADDRESS: juzwystawiam@quickpaper.online
      MAIL_FROM_NAME: Juz Wystawiam
      MAIL_MAILER: smtp
      MAIL_HOST: postal.quickpaper.online
      MAIL_PORT: 25
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    networks:
      - app_prod
    volumes:
      - type: bind
        source: /var/www/html/prod/storage
        target: /var/www/html/storage/app/public

  queue_worker:
    container_name: queue_worker_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      APP_URL: https://www.juzwystawiam.pl
      ASSET_URL: https://www.juzwystawiam.pl
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: db_prod
      DB_USERNAME: db_prod_user
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ENV: production
      APP_DEBUG: false
      VITE_APP_NAME: JuzWystawiam
      APP_NAME: JuzWystawiam
      MAIL_FROM_ADDRESS: juzwystawiam@quickpaper.online
      MAIL_FROM_NAME: Juz Wystawiam
      MAIL_MAILER: smtp
      MAIL_HOST: postal.quickpaper.online
      MAIL_PORT: 25
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      RESEND_KEY: ${RESEND_KEY}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    command: >
      sh -c "php artisan queue:work --sleep=3 --tries=3 --timeout=60"
    restart: unless-stopped
    networks:
      - app_prod

  db:
    image: postgres:17.6
    container_name: db_prod
    volumes:
      - db_data_prod:/postgresql
    environment:
      POSTGRES_DB: db_prod
      POSTGRES_USER: db_prod_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_prod

volumes:
  db_data_prod:

networks:
  app_prod:
