services:
  app:
    container_name: app_stg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8000'
    environment:
      APP_URL: https://www.juzwystawiam.pl
      ASSET_URL: https://www.juzwystawiam.pl
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: db_stg
      DB_USERNAME: db_stg_user
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ENV: production
      APP_DEBUG: false
      VITE_APP_NAME: JuzWystawiam
      APP_NAME: JuzWystawiam
      MAIL_MAILER: resend
      MAIL_FROM_ADDRESS: invoice@juzwystawiam.pl
      MAIL_FROM_NAME: JuzWystawiam
      MAIL_HOST: https://www.juzwystawiam.pl
      RESEND_KEY: ${RESEND_KEY}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    networks:
      - app_stg_stg
    volumes:
      - type: bind
        source: /var/www/html/stg/storage
        target: /var/www/html/storage/app/public

  queue_worker:
    container_name: queue_worker_stg
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_URL: https://www.juzwystawiam.pl
      ASSET_URL: https://www.juzwystawiam.pl
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: db_stg
      DB_USERNAME: db_stg_user
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ENV: production
      APP_DEBUG: false
      VITE_APP_NAME: JuzWystawiam
      APP_NAME: JuzWystawiam
      MAIL_MAILER: resend
      MAIL_FROM_ADDRESS: invoice@juzwystawiam.pl
      MAIL_FROM_NAME: JuzWystawiam
      MAIL_HOST: https://www.juzwystawiam.pl
      RESEND_KEY: ${RESEND_KEY}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    command: >
      sh -c "php artisan queue:work --sleep=3 --tries=3 --timeout=60"
    restart: unless-stopped
    networks:
      - app_stg_stg

  db:
    image: postgres:17.6
    container_name: db_stg
    volumes:
      - db_data_stg:/postgresql
    environment:
      POSTGRES_DB: db_stg
      POSTGRES_USER: db_stg_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_stg_stg

volumes:
  db_data_stg:

networks:
  app_stg_stg:
