services:
  app:
    container_name: app_stg
    volumes:
      - /var/www/html/stg:/app
    environment:
      VITE_APP_NAME: JuzWystawiam
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_DEBUG: false
      APP_URL: https://staging.juzwystawiam.pl
      ASSET_URL: https://staging.juzwystawiam.pl
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: resend
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 2525
      MAIL_FROM_ADDRESS: invoice@juzwystawiam.pl
      MAIL_FROM_NAME: JuzWystawiam
      RESEND_KEY: ${RESEND_KEY}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 9001:9000

  queue-worker:
    container_name: queue_worker_stg
    volumes:
      - /var/www/html/stg:/app
    build:
      dockerfile: Dockerfile
    command: php artisan queue:work
    environment:
      IS_WORKER: true
      VITE_APP_NAME: JuzWystawiam
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_DEBUG: false
      APP_URL: https://staging.juzwystawiam.pl
      ASSET_URL: https://staging.juzwystawiam.pl
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: resend
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 2525
      MAIL_FROM_ADDRESS: invoice@juzwystawiam.pl
      MAIL_FROM_NAME: JuzWystawiam
      RESEND_KEY: ${RESEND_KEY}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    restart: unless-stopped

  db:
    image: postgres:17.6
    container_name: db_stg
    volumes:
      - db-volume-stg:/postgresql
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  db-volume-stg:
