services:
  app:
    container_name: app_stg
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8001:8000'
    environment:
      APP_URL: https://staging.juzwystawiam.pl
      ASSET_URL: https://staging.juzwystawiam.pl
      DB_CONNECTION: pgsql
      DB_SCHEMA: staging_juzwystawiam
      DB_URL: ${DB_URL}
      APP_ENV: production
      APP_DEBUG: false
      VITE_APP_NAME: JuzWystawiam
      APP_NAME: JuzWystawiam
      MAIL_FROM_ADDRESS: juzwystawiam@quickpaper.online
      MAIL_FROM_NAME: Juz Wystawiam
      MAIL_MAILER: smtp
      MAIL_HOST: postal.quickpaper.online
      MAIL_PORT: 25
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    volumes:
      - type: bind
        source: /var/www/html/stg/storage
        target: /var/www/html/storage/app/public

  queue_worker:
    container_name: queue_worker_stg
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      APP_URL: https://staging.juzwystawiam.pl
      ASSET_URL: https://staging.juzwystawiam.pl
      DB_CONNECTION: pgsql
      DB_SCHEMA: staging_juzwystawiam
      DB_URL: ${DB_URL}
      APP_ENV: production
      APP_DEBUG: false
      VITE_APP_NAME: JuzWystawiam
      APP_NAME: JuzWystawiam
      MAIL_FROM_ADDRESS: juzwystawiam@quickpaper.online
      MAIL_FROM_NAME: Juz Wystawiam
      MAIL_MAILER: smtp
      MAIL_HOST: postal.quickpaper.online
      MAIL_PORT: 25
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    command: >
      sh -c "php artisan queue:work --sleep=3 --tries=3 --timeout=60"
    restart: unless-stopped

networks:
  app_stg:
