name: Production deploy

on:
  workflow_dispatch:

jobs:
  pest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Start Docker Stack
        run: |
          sleep 5
          docker compose up -d

      - name: Tests
        run: docker compose exec app php artisan test

  quality:
    needs: pest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: vendor/bin/pint

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

  deploy:
    needs: quality
    timeout-minutes: 10
    environment: prod
    runs-on: self-hosted
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

    defaults:
      run:
        working-directory: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: prod

      - name: Remove stopped containers
        run: |
          docker ps -a -q --filter status=exited | xargs -r docker rm

      - name: Remove dangling images
        run: |
          docker images -f "dangling=true" -q | xargs -r docker rmi

      - name: db
        run: docker compose -f docker-compose.prod.yml up -d db

      - name: Debug Environment Variables
        run: env | sort

      - name: app
        run: |
          docker compose -f docker-compose.prod.yml up -d --build --force-recreate app
          sleep 5

      - name: queue-worker
        run: |
          docker compose -f docker-compose.prod.yml up -d --build --force-recreate queue_worker
          sleep 5

      - name: export-static
        run: ./scripts/export-static.sh -c app_prod /var/www/html/prod/

      - name: Prune Docker
        run: docker system prune -f
